### ISSUE TITLE
udp.peek() always returning -1, even when bytes are available

### ISSUE THREAD

**Issue by MrWFoulkes** [arduino-libraries/MKRGSM#106]
With the same code as issue #105, `udp.peek()` is always returning -1.

Here's the serial output:
```
Attempting to connect to the modem

Attempting to connect to the GPRS Access Point Name

Packet sent
Awaiting response
udp.parsePacket 48
udp.available -48
udp.peek -1 <--- expected decimal 36 (first byte in response)
```

The code is the same as #105 and quite long so I won't post it again.

**Comment by Rocketct** [comment]
i'll close this issue because of: https://github.com/arduino-libraries/MKRGSM/pull/107
