### ISSUE TITLE
Platform IO

### ISSUE THREAD

**Issue by fabltd** [arduino-libraries/MKRGSM#125]
Hi 

This is not working in the latest Platform IO. I have no idea why. Will work in the Arduino IDE but not platform IO. Really Strange.

Any thoughts?

**Comment by per1234** [comment]
Please report any bugs related to incompatibilities in the PlatformIO framework to the appropriate PlatformIO issue tracker. Arduino only provides support for using libraries with the official Arduino software.

**Comment by fabltd** [comment]
This is a bug with the Lib. Platform IO works well except this Lib.
