### ISSUE TITLE
Finding some type struct

### ISSUE THREAD

**Issue by kotito** [arduino-libraries/MKRGSM#148]
Hello.

I was studying your code and I have a doubt about variables in Modem.h
In that file you have some private variables like Uart* _uart, String _buffer and static Print* _debugPrint
What file those variables come from?

I hope you can guide the way to get them. Thanks

**Comment by per1234** [comment]
Hi @kotito. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
