### ISSUE TITLE
Porting MKRGSM to Leonardo

### ISSUE THREAD

**Issue by pjneder** [arduino-libraries/MKRGSM#161]
Note: This problem may be related to the open issue https://github.com/arduino-libraries/MKRGSM/issues/160

I have some older Leonardo boards and a slightly different uBlox modem, so I wanted to port MKRGSM library. It is based off the now deprecated GSM library which used the SoftwareSerial library, causing other headaches.

If I tweak modem.cpp in the library to this:
`ModemClass MODEM(Serial1, 115200, 4, 7);`

Similar to the other issue I get this compile error:

```text
WARNING: library MKRGSM claims to run on samd architecture(s) and may be incompatible with your current board which runs on avr architecture(s).
In file included from \Arduino\libraries\MKRGSM\src/GSMVoiceCall.h:23:0,
                 from \Arduino\libraries\MKRGSM\src/MKRGSM.h:24,
                 from \AppData\Local\Temp\.arduinoIDE-unsaved2023123-26736-sy7p7s.4vyce\TestModem\TestModem.ino:18:
\Arduino\libraries\MKRGSM\src/Modem.h:35:18: error: expected ')' before '&' token
   ModemClass(Uart& uart, unsigned long baud, int resetPin, int dtrPin);
                  ^
\Arduino\libraries\MKRGSM\src/Modem.h:71:3: error: 'Uart' does not name a type; did you mean 'sqrt'?
   Uart* _uart;
   ^~~~
   sqrt

exit status 1
```

I am afraid my C++ skillz are not quite up to figuring out why that constructor hates me for passing in `Serial1` instead of `SerialGSM`

Any help is greatly appreciated!

**Comment by per1234** [comment]
Hi . Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
