### ISSUE TITLE
MKR GSM 1400 Standby mode and Alarm

### ISSUE THREAD

**Issue by Marcos151196** [arduino-libraries/MKRGSM#18]
Hi,

I'm making a Iot project and I need my arduino to go to sleep mode (everything powered down) and wake up after a time that I want to specify myself.

Power consumption is a big deal in my project so I want to reduce it as much as possible.

I've tried the RTCZero library examples but for some reason they don't work on my board (I should be able to see "Awake!!" on the serial monitor but function "Alarma" is never called for some reason):

```
rtc.begin();
   rtc.setTime(16,0,0);
   rtc.setDate(20,03,18);
   
   rtc.setAlarmTime(16,0,10);
   
   rtc.enableAlarm(rtc.MATCH_HHMMSS);

   rtc.attachInterrupt(Alarma);
   //rtc.standbyMode();
   

}

void Alarma(){
  Serial.println("Awake!!");
}
```

Any suggestions about how I should do this?

Thanks in advance.

**Comment by Marcos151196** [comment]
I used this code and the LED does not switch on:
```
#include <MKRGSM.h>
#include <RTCZero.h>

RTCZero rtc;
void Alarma();


void setup() {
 delay(5000);
 Serial.begin(9600);
 pinMode(LED_BUILTIN,OUTPUT);
}

void loop() {
  delay(5000);
  digitalWrite(LED_BUILTIN, LOW);
  rtc.begin();
  rtc.setTime(16,0,0);
  rtc.setDate(20,03,18);
  
  rtc.setAlarmTime(16,0,10);
  
  rtc.enableAlarm(rtc.MATCH_HHMMSS);
  rtc.attachInterrupt(Alarma);
  rtc.standbyMode();
   
}

void Alarma(){
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  digitalWrite(LED_BUILTIN, LOW);
}
```

**Comment by facchinm** [comment]
I can see the LED_BUILTIN lighting up with your same sketch. I'm using RTCZero version 1.5.1 and SAMD core 1.6.18.
I removed 
```
delay(1000);
digitalWrite(LED_BUILTIN, LOW);
```
since it executes in interrupt context, better avoid long delays (and the LED will be brought back to LOW on the next loop())

**Comment by Rocketct** [comment]
Hi all, @Marcos151196 i have test your sketch and it works fine also for me, i have removed 

`delay(1000);
digitalWrite(LED_BUILTIN, `LOW);`

moreover i have change the LED_BUILTIN for a pin and measured the variation of the output and it works also in this case.
I'm using RTCZero version 1.5.1 and SAMD core 1.6.18 like @facchinm.

**Comment by jcrocker** [comment]
I am using an MKR 1400.  I modified the code as follows, and this works for me - the light comes on 10 seconds after the device starts up

`#include <MKRGSM.h>
#include <RTCZero.h>

RTCZero rtc;
void ISR();

const byte seconds = 0;
const byte minutes = 0;
const byte hours = 0;

const byte day = 28;
const byte month = 6;
const byte year = 18;

void setup() {
  delay(5000);
  pinMode(LED_BUILTIN,OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
  
  rtc.begin();
  rtc.setTime(hours, minutes, seconds);
  rtc.setDate(day, month, year);
  
  rtc.setAlarmTime(00,00,10);
  
  rtc.enableAlarm(rtc.MATCH_HHMMSS);
  rtc.attachInterrupt(ISR);
  rtc.standbyMode();
}

void loop() {   
}

void ISR(){
  digitalWrite(LED_BUILTIN, HIGH);
}`

**Comment by sandeepmistry** [comment]
Closing as the feature seems to work. Also it's unrelated to this library.
