### ISSUE TITLE
GSMClient::write(uint8_t c) bug

### ISSUE THREAD

**Issue by ardiri** [arduino-libraries/MKRGSM#32]
this can cause weird behaviour; the correct implementation should be

```
size_t GSMClient::write(uint8_t c)
{
  return write(&c, 1);
}
```

in it's current form; it'll call another function where it'll try to determine the string length at the address of 'c' - which, may be followed by a null char; or may not.

https://github.com/arduino-libraries/MKRGSM/blob/367beb77b64e738edd4652c833328b395d6331a7/src/GSMClient.cpp#L230

**Comment by sandeepmistry** [comment]
This has been fixed in PR #34 by @Rocketct.

Within the hour, there will be a new v1.2.0 version of the library in the library manager that includes the fix.
