### ISSUE TITLE
Allow SSL connection without certs

### ISSUE THREAD

**Issue by Josca** [arduino-libraries/MKRGSM#40]
Hi,

 I need to connect to my HTTPS website without valid certificate from my MKR GSM 1400. I use GSMSSLClient for that. I see there is no option for this currently. I would like to add something like `-k` switch in `curl` or `verify` param in python `requests`.

Could you recommend me how to do that?

**Comment by jgartner1** [comment]
If your certificate is not valid why even connecting over an unsafe connection like that, wich can get interferred pretty much as easily as using regular http connections? Just connect via port 80 instead of 443 and ensure the server where the request goes to supports port 80 aswell and doesn't just redirect you to 443 (https). From a security point of view it's equally safe. 

Or if you want true encryption I suggest you create yourself a free valid certificate signed by a CA. For this I would recommend LetsEncrypt. With an online-tool like https://www.sslforfree.com/ you can even create your signed certificates online without instally any software on your server.

**Comment by Josca** [comment]
HTTPS connection is secure (encrypted) even without valid certificate see, so it's better then HTTP.

I already tried LetsEncrypt using command line tool, but I was not successful. It ended with errors. Maybe it's not possible get valid certificate for long domain like `ec2-35-138-22-53.eu-central-1.compute.amazonaws.com`.

**Comment by FrancMunoz** [comment]
Hi!

SARA modem is configured by default to not validate certificates, the AT command used for configure that is +USECPRF, see [manual](https://www.u-blox.com/sites/default/files/u-blox-CEL_ATCommands_%28UBX-13002752%29.pdf) at page 629.

Sending AT+USECPRF=0,0,0 to modem will change certificate validation level to no validation. All in all this is the default option, so nothing will be changed:

> 0: certificate validation level; allowed values for <param_val>:
> - 0 (factory-programmed value): **Level 0 - No validation; the server certificate will not be checked or**
> **verified. The server in this case is not authenticated.**
> - 1: Level 1 - Root certificate validation without URL integrity check. The server certificate will be verified
> with a specific trusted certificates or with each of the imported trusted root certificates.
> - 2: Level 2 - Root certificate validation with URL integrity check. Level 1 validation with an additional
> URL integrity check.
> - 3: Level 3 - Root certificate validation with check of certificate validity date. Level 2 validation with an
> additional check of certificate validity date.
> 

I guess your problem is about the function called to connect. If you want to use SSL you should use `GSMClient::connectSSL` instead of `GSMClient::connect`.

I've just make a PR #42 that is basically a function to download a string using HTTP or HTTPs, just take a look at the PR. 

I've used SSL using `GSMClient::connectSSL` and it worked for me without issues.

**Comment by Rocketct** [comment]
Hi all, @Josca, we doesn't support SSL connection without certs, with the PR https://github.com/arduino-libraries/MKRGSM/pull/56  we set this  level of certificates validation: 

> 1: Level 1 - Root certificate validation without URL integrity check. The server certificate will be verified

you can find the certificates in https://github.com/arduino-libraries/MKRGSM/blob/master/src/utility/GSMRootCerts.h

i'll close the issue.

**Comment by darleys** [comment]
Still, this is not resolving https sites, What is the process to access https . The GSMRootCerts.h is not sufficient for many websites.

**Comment by beenjamminnallday** [comment]
Hello all, I am using an MKRGSM 1400 and attempting to connect on a website a friend on mind created. So far the website is supposed to only return {"message":"Success","status":200}. 
I had issues even connecting to the server but I was able to resolve this by using _MODEM.sendf("AT+USECPRF=0,0,0");_ to change the modem certificate validation level to no validation. 
However, another issue comes up where when attempting to connect to a https server/website and perform a GET request, I get _301 Moved Permanently_. My hypothesis was that it is performing the HTTP request but cannot/does not redirect me to the website. 

Unfortunately, I am no longer able to get this error message. Any help on this issue would be appreciated. I am simply trying to connect to a web server, i'm a relative beginner but I assume this should be straight forward and is supported by the device.

Attached is the code and my serial output.

```
/*
  Web client

 This sketch connects to a website using SSL through a MKR GSM 1400 board. Specifically,
 this example downloads the URL "http://www.arduino.cc/asciilogo.txt" and
 prints it to the Serial monitor.

 Circuit:
 * MKR GSM 1400 board
 * Antenna
 * SIM card with a data plan

 created 8 Mar 2012
 by Tom Igoe
*/

// libraries
#include <MKRGSM.h>

#include "arduino_secrets.h" 
// Please enter your sensitive data in the Secret tab or arduino_secrets.h
// PIN Number
const char PINNUMBER[]     = SECRET_PINNUMBER;
// APN data
const char GPRS_APN[]      = SECRET_GPRS_APN;
const char GPRS_LOGIN[]    = SECRET_GPRS_LOGIN;
const char GPRS_PASSWORD[] = SECRET_GPRS_PASSWORD;

// initialize the library instance
GSMSSLClient client;
GPRS gprs;
GSM gsmAccess(true);

//URL, path and port (for example: arduino.cc)
char server[] = "dashboard.instant-alert.ca";
char path[] = "/";
int port = 443; // port 443 is the default for HTTPS

void setup() {
  // initialize serial communications and wait for port to open:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
 MODEM.debug();
  Serial.println("Starting Arduino web client.");
  // connection state
  bool connected = false;

  // After starting the modem with GSM.begin()
  // attach the shield to the GPRS network with the APN, login and password
  while (!connected) {
    if ((gsmAccess.begin(PINNUMBER) == GSM_READY) &&
        (gprs.attachGPRS(GPRS_APN, GPRS_LOGIN, GPRS_PASSWORD) == GPRS_READY)) {
      connected = true;
    } else {
      Serial.println("Not connected");
      delay(1000);
    }
  }

  Serial.println("connecting...");

  // if you get a connection, report back via serial:
  //MODEM.sendf("AT+USECPRF=0,0,0");
  if (client.connect(server, port)) {
    Serial.println("connected");
    // Make a HTTP request:
    client.print("GET ");
    client.print(path);
    client.println(" HTTP/1.1");
    client.print("Host: ");
    client.print(server);
    client.println("Connection: close");
    client.println();
  } else {
    // if you didn't get a connection to the server:
    Serial.println("connection failed");
  }
}

void loop() {
  // if there are incoming bytes available
  // from the server, read them and print them:
  if (client.available()) {
    char c = client.read();
    Serial.print(c);
  }
  
  // if the server's disconnected, stop the client:
  if (!client.available() && !client.connected()) {
    Serial.println();
    Serial.println("disconnecting.");
    client.stop();

    // do nothing forevermore:
    for (;;)
      ;
  }
}
```



**OUTPUT**

```
Starting Arduino web client.
⸮AT

OK
AT+IPR=921600

OK
AT

OK
AT+UPSV=3

OK
AT+CPIN?

ERROR
AT+CPIN?

ERROR
AT+CPIN?

+CPIN: READY

OK

+PACSP1
AT+CMGF=1

OK
AT+UDCONF=1,1

OK
AT+CTZU=1

OK
AT+UDTMFD=1,2

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK

+UMWI: 0,1

+UMWI: 0,2

+UMWI: 0,3

+UMWI: 0,4
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,1

OK
AT+UCALLSTAT=1

OK
AT+CGATT=1

OK
AT+UPSD=0,1,"m2minternet.apn"

OK
AT+UPSD=0,6,3

OK
AT+UPSD=0,2,""

OK
AT+UPSD=0,3,""

OK
AT+UPSD=0,7,"0.0.0.0"

OK
AT+UPSDA=0,3

OK
AT+UPSND=0,8

+UPSND: 0,8,1

OK
connecting...
AT+USECMNG=0,0,"AddTrust_External_CA_Root",1082
>
+USECMNG: 0,0,"AddTrust_External_CA_Root","1d3554048578b03f42424dbf20730a3f"

OK
AT+USECMNG=0,0,"Baltimore_CyberTrust_Root",891
>
+USECMNG: 0,0,"Baltimore_CyberTrust_Root","acb694a59c17e0d791529bb19706a6e4"

OK
AT+USECMNG=0,0,"COMODO_RSA_Certification_Authority",1500
>
+USECMNG: 0,0,"COMODO_RSA_Certification_Authority","1b31b0714036cc143691adc43efdec18"

OK
AT+USECMNG=0,0,"DST_Root_CA_X3",846
>
+USECMNG: 0,0,"DST_Root_CA_X3","410352dc0ff7501b16f0028eba6f45c5"

OK
AT+USECMNG=0,0,"DigiCert_High_Assurance_EV_Root_CA",969
>
+USECMNG: 0,0,"DigiCert_High_Assurance_EV_Root_CA","d474de575c39b2d39c8583c5c065498a"

OK
AT+USECMNG=0,0,"Entrust_Root_Certification_Authority",1173
>
+USECMNG: 0,0,"Entrust_Root_Certification_Authority","d6a5c3ed5ddd3e00c13d87921f1d3fe4"

OK
AT+USECMNG=0,0,"Equifax_Secure_Certificate_Authority",804
>
+USECMNG: 0,0,"Equifax_Secure_Certificate_Authority","67cb9dc013248a829bb2171ed11becd4"

OK
AT+USECMNG=0,0,"GeoTrust_Global_CA",856
>
+USECMNG: 0,0,"GeoTrust_Global_CA","f775ab29fb514eb7775eff053c998ef5"

OK
AT+USECMNG=0,0,"GeoTrust_Primary_Certification_Authority_G3",1026
>
+USECMNG: 0,0,"GeoTrust_Primary_Certification_Authority_G3","b5e83436c910445848706d2e83d4b805"

OK
AT+USECMNG=0,0,"GlobalSign",958
>
+USECMNG: 0,0,"GlobalSign","9414777e3e5efd8f30bd41b0cfe7d030"

OK
AT+USECMNG=0,0,"Go_Daddy_Root_Certificate_Authority_G2",969
>
+USECMNG: 0,0,"Go_Daddy_Root_Certificate_Authority_G2","803abc22c1e6fb8d9b3b274a321b9a01"

OK
AT+USECMNG=0,0,"VeriSign_Class_3_Public_Primary_Certification_Authority_G5",1239
>
+USECMNG: 0,0,"VeriSign_Class_3_Public_Primary_Certification_Authority_G5","cb17e431673ee209fe455793f30afa1c"

OK
AT+USECMNG=2,0,"AmazonRootCA1"

ERROR
AT+USECMNG=0,0,"Starfield_Services_Root_Certificate_Authority_G2",1011
>
+USECMNG: 0,0,"Starfield_Services_Root_Certificate_Authority_G2","173574af7b611cebf4f93ce2ee40f9a2"

OK
AT+USOCR=6

+USOCR: 0

OK
AT+USOSEC=0,1,0

OK
AT+USECPRF=0,0,1

OK
AT+USOCO=0,"dashboard.instant-alert.ca",443

ERROR

+UUSOCL: 0
AT+USOCL=0

ERROR
connection failed

disconnecting.
```
