### ISSUE TITLE
Connection via GSMSSLclient only works once

### ISSUE THREAD

**Issue by jgartner1** [arduino-libraries/MKRGSM#41]
I created a wrapper class to make a request to a webserver multiple times. But it only works when I execute the request-function in the setup()-function. And even then it only works once. I've made a detailed explanation of this on the Arduino Stack Exchange, which can be found here: https://arduino.stackexchange.com/questions/55862/gsmsslclient-only-works-once

Does anyone know a solution to this or has experienced similar errors?

**Comment by sandeepmistry** [comment]
@jgartner1 could you please provide an Arduino sketch here that can be used to reproduce the issue?

**Comment by sandeepmistry** [comment]
Closing due to lack of feedback.
