### ISSUE TITLE
MKR1400 BUGS WITH 1 CHAR SMS AND SPACE CHAR SMS

### ISSUE THREAD

**Issue by gbtassara** [arduino-libraries/MKRGSM#63]
I have used ARDUINO 1.8.7. To duplicate the bugs:

- first upload the standard "ReceiveSMS" example (see it at the end of this article)

then try the following:

- if you send a single SPACE char SMS or a SMS with ONLY SPACE chars you will see the following output

Message received from:
+39xxxx187088
+CMGL: 15,"REC UNREAD","+39xxxx187088",,"18/11/15,10:08:43+04"
END OF MESSAGE
MESSAGE DELETED

- instead if you send a single CHAR SMS (except for the SINGLE SPACE SMS case), there will be no output from the board.

I SUPPOSE THERE IS A BUG WITH THE LIBRARY

[ReceiveSMS.zip](https://github.com/arduino-libraries/MKRGSM/files/2584546/ReceiveSMS.zip)

**Comment by Milan991** [comment]
I have similar problem, I couldn't receive one character SMS.

**Comment by Rocketct** [comment]
Hi all @gbtassara, thanks for open the issue, the #67 resolve this problem, if you want test an let me know if works, from my side all was going fine.
